runtime: nodejs14
handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /*
    secure: always
    script: auto
env_variables:
  APP_ENV: <APP_ENV>
  REVISION_HASH: <REVISION_HASH>
  REVISION_TIMESTAMP: <REVISION_TIMESTAMP>
