runtime: nodejs14
handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /*
    secure: always
    script: auto
env_variables:
  APP_ENV: <APP_ENV>
  GCP_PROJECT_ID: <GCP_PROJECT_ID>
  GCP_BUCKET_NAME: <GCP_BUCKET_NAME>
  GCP_CLIENT_EMAIL: <GCP_CLIENT_EMAIL>
  GCP_PRIVATE_KEY: <GCP_PRIVATE_KEY>
  REVISION_HASH: <REVISION_HASH>
  REVISION_TIMESTAMP: <REVISION_TIMESTAMP>
