name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build app
        run: |
          npm i --production=false
          npm run build
          npm i --production

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS_JSON}}
          export_default_credentials: true

      - name: Set env
        shell: bash -eux {0}
        run: |
          sed -i -e 's/<REVISION_HASH>/${{ env.REVISION_HASH }}/g' app.yaml
          sed -i -e 's/<REVISION_TIMESTAMP>/$(date +%s)/g' app.yaml
        env:
          REVISION_HASH: ${{ github.sha }}

      - name: Deploy app
        run: gcloud app deploy -q --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Notify result to slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Deploy to Production*'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
